### Machine Learning: Regression - Predicting Energy Efficiency of Buildings

### AMADI CHIMEREMMA SANDRA
 
 1572c1a4b801f000

In [35]:
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import  r2_score,mean_absolute_error, mean_squared_error
%matplotlib inline
import warnings

warnings.filterwarnings("ignore")

In [9]:
df_energy = pd.read_csv("energydata_complete.csv")
df_energy.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [10]:
df_energy.describe().T

,count,mean,std,min,25%,50%,75%,max
Appliances,19735.0,97.694958,102.524891,10.000000,50.000000,60.000000,100.000000,1080.000000
lights,19735.0,3.801875,7.935988,0.000000,0.000000,0.000000,0.000000,70.000000
T1,19735.0,21.686571,1.606066,16.790000,20.760000,21.600000,22.600000,26.260000
RH_1,19735.0,40.259739,3.979299,27.023333,37.333333,39.656667,43.066667,63.360000
T2,19735.0,20.341219,2.192974,16.100000,18.790000,20.000000,21.500000,29.856667
RH_2,19735.0,40.420420,4.069813,20.463333,37.900000,40.500000,43.260000,56.026667
T3,19735.0,22.267611,2.006111,17.200000,20.790000,22.100000,23.290000,29.236000
RH_3,19735.0,39.242500,3.254576,28.766667,36.900000,38.530000,41.760000,50.163333
T4,19735.0,20.855335,2.042884,15.100000,19.530000,20.666667,22.100000,26.200000
RH_4,19735.0,39.026904,4.341321,27.660000,35.530000,38.400000,42.156667,51.090000
T5,19735.0,19.592106,1.844623,15.330000,18.277500,19.390000,20.619643,25.795000
RH_5,19735.0,50.949283,9.022034,29.815000,45.400000,49.090000,53.663333,96.321667
T6,19735.0,7.910939,6.090347,-6.065000,3.626667,7.300000,11.256000,28.290000
RH_6,19735.0,54.609083,31.149806,1.000000,30.025000,55.290000,83.226667,99.900000
T7,19735.0,20.267106,2.109993,15.390000,18.700000,20.033333,21.600000,26.000000
RH_7,19735.0,35.388200,5.114208,23.200000,31.500000,34.863333,39.000000,51.400000
T8,19735.0,22.029107,1.956162,16.306667,20.790000,22.100000,23.390000,27.230000
RH_8,19735.0,42.936165,5.224361,29.600000,39.066667,42.375000,46.536000,58.780000
T9,19735.0,19.485828,2.014712,14.890000,18.000000,19.390000,20.600000,24.500000
RH_9,19735.0,41.552401,4.151497,29.166667,38.500000,40.900000,44.338095,53.326667
T_out,19735.0,7.411665,5.317409,-5.000000,3.666667,6.916667,10.408333,26.100000
Press_mm_hg,19735.0,755.522602,7.399441,729.300000,750.933333,756.100000,760.933333,772.300000
RH_out,19735.0,79.750418,14.901088,24.000000,70.333333,83.666667,91.666667,100.000000
Windspeed,19735.0,4.039752,2.451221,0.000000,2.000000,3.666667,5.500000,14.000000
Visibility,19735.0,38.330834,11.794719,1.000000,29.000000,40.000000,40.000000,66.000000
Tdewpoint,19735.0,3.760707,4.194648,-6.600000,0.900000,3.433333,6.566667,15.500000
rv1,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
rv2,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530

In [13]:
#COLUMN RENAMING
column_rename = {'T1':'temp_kitchen', 'T2': 'temp_livingroom', 'T3':'temp_laundry', 'T4': 'temp_office', 
                 'T5':'temp_bathroom', 'T6': 'temp_outside_northside', 'T7':'temp_ironing', 'T8': 'temp_teenagerroom', 
                'RH_1':  'humidity_kitchen', 'RH_2': 'humidity_livingroom', 'RH_3': 'humidity_laundry',
                'RH_4': 'humidity_office', 'RH_5': 'humidity_bathroom', 
                'RH_6': 'humidity_outside', 'RH_7':  'humidity_ironing', 'RH_8': 'humidity_teenagerroom',
                'RH_9':  'humidity_parentroom', 'rv1': 'random_variable1','rv2': 'random_variable2',
                'T9':'temp_parentroom', 'T_out': 'temp_outside','RH_out':  'humidity_outside', }

df_energy = df_energy.rename(columns=column_rename)
df_energy

,date,Appliances,lights,temp_kitchen,humidity_kitchen,temp_livingroom,humidity_livingroom,temp_laundry,humidity_laundry,temp_office,...,temp_parentroom,humidity_parentroom,temp_outside,Press_mm_hg,humidity_outside,Windspeed,Visibility,Tdewpoint,random_variable1,random_variable2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [15]:
df_energy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    19735 non-null  object
 1   Appliances              19735 non-null  int64
 2   lights                  19735 non-null  int64
 3   temp_kitchen            19735 non-null  float64
 4   humidity_kitchen        19735 non-null  float64
 5   temp_livingroom         19735 non-null  float64
 6   humidity_livingroom     19735 non-null  float64
 7   temp_laundry            19735 non-null  float64
 8   humidity_laundry        19735 non-null  float64
 9   temp_office             19735 non-null  float64
 10  humidity_office         19735 non-null  float64
 11  temp_bathroom           19735 non-null  float64
 12  humidity_bathroom       19735 non-null  float64
 13  temp_outside_northside  19735 non-null  float64
 14  humidity_outside        19735 non-null  float64
 15  temp_ironing            19735 non-null  float64
 16  humidity_ironing        19735 non-null  float64
 17  temp_teenagerroom       19735 non-null  float64
 18  humidity_teenagerroom   19735 non-null  float64
 19  temp_parentroom         19735 non-null  float64
 20  humidity_parentroom     19735 non-null  float64
 21  temp_outside            19735 non-null  float64
 22  Press_mm_hg             19735 non-null  float64
 23  humidity_outside        19735 non-null  float64
 24  Windspeed               19735 non-null  float64
 25  Visibility              19735 non-null  float64
 26  Tdewpoint               19735 non-null  float64
 27  random_variable1        19735 non-null  float64
 28  random_variable2        19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [21]:
df_energy.isnull().sum()

date                      0
Appliances                0
lights                    0
temp_kitchen              0
humidity_kitchen          0
temp_livingroom           0
humidity_livingroom       0
temp_laundry              0
humidity_laundry          0
temp_office               0
humidity_office           0
temp_bathroom             0
humidity_bathroom         0
temp_outside_northside    0
humidity_outside          0
temp_ironing              0
humidity_ironing          0
temp_teenagerroom         0
humidity_teenagerroom     0
temp_parentroom           0
humidity_parentroom       0
temp_outside              0
Press_mm_hg               0
humidity_outside          0
Windspeed                 0
Visibility                0
Tdewpoint                 0
random_variable1          0
random_variable2          0
dtype: int64

In [23]:
df_energy.describe().T

,count,mean,std,min,25%,50%,75%,max
Appliances,19735.0,97.694958,102.524891,10.000000,50.000000,60.000000,100.000000,1080.000000
lights,19735.0,3.801875,7.935988,0.000000,0.000000,0.000000,0.000000,70.000000
temp_kitchen,19735.0,21.686571,1.606066,16.790000,20.760000,21.600000,22.600000,26.260000
humidity_kitchen,19735.0,40.259739,3.979299,27.023333,37.333333,39.656667,43.066667,63.360000
temp_livingroom,19735.0,20.341219,2.192974,16.100000,18.790000,20.000000,21.500000,29.856667
humidity_livingroom,19735.0,40.420420,4.069813,20.463333,37.900000,40.500000,43.260000,56.026667
temp_laundry,19735.0,22.267611,2.006111,17.200000,20.790000,22.100000,23.290000,29.236000
humidity_laundry,19735.0,39.242500,3.254576,28.766667,36.900000,38.530000,41.760000,50.163333
temp_office,19735.0,20.855335,2.042884,15.100000,19.530000,20.666667,22.100000,26.200000
humidity_office,19735.0,39.026904,4.341321,27.660000,35.530000,38.400000,42.156667,51.090000
temp_bathroom,19735.0,19.592106,1.844623,15.330000,18.277500,19.390000,20.619643,25.795000
humidity_bathroom,19735.0,50.949283,9.022034,29.815000,45.400000,49.090000,53.663333,96.321667
temp_outside_northside,19735.0,7.910939,6.090347,-6.065000,3.626667,7.300000,11.256000,28.290000
humidity_outside,19735.0,54.609083,31.149806,1.000000,30.025000,55.290000,83.226667,99.900000
temp_ironing,19735.0,20.267106,2.109993,15.390000,18.700000,20.033333,21.600000,26.000000
humidity_ironing,19735.0,35.388200,5.114208,23.200000,31.500000,34.863333,39.000000,51.400000
temp_teenagerroom,19735.0,22.029107,1.956162,16.306667,20.790000,22.100000,23.390000,27.230000
humidity_teenagerroom,19735.0,42.936165,5.224361,29.600000,39.066667,42.375000,46.536000,58.780000
temp_parentroom,19735.0,19.485828,2.014712,14.890000,18.000000,19.390000,20.600000,24.500000
humidity_parentroom,19735.0,41.552401,4.151497,29.166667,38.500000,40.900000,44.338095,53.326667
temp_outside,19735.0,7.411665,5.317409,-5.000000,3.666667,6.916667,10.408333,26.100000
Press_mm_hg,19735.0,755.522602,7.399441,729.300000,750.933333,756.100000,760.933333,772.300000
humidity_outside,19735.0,79.750418,14.901088,24.000000,70.333333,83.666667,91.666667,100.000000
Windspeed,19735.0,4.039752,2.451221,0.000000,2.000000,3.666667,5.500000,14.000000
Visibility,19735.0,38.330834,11.794719,1.000000,29.000000,40.000000,40.000000,66.000000
Tdewpoint,19735.0,3.760707,4.194648,-6.600000,0.900000,3.433333,6.566667,15.500000
random_variable1,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
random_variable2,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530

In [24]:
df_energy.count()

date                      19735
Appliances                19735
lights                    19735
temp_kitchen              19735
humidity_kitchen          19735
temp_livingroom           19735
humidity_livingroom       19735
temp_laundry              19735
humidity_laundry          19735
temp_office               19735
humidity_office           19735
temp_bathroom             19735
humidity_bathroom         19735
temp_outside_northside    19735
humidity_outside          19735
temp_ironing              19735
humidity_ironing          19735
temp_teenagerroom         19735
humidity_teenagerroom     19735
temp_parentroom           19735
humidity_parentroom       19735
temp_outside              19735
Press_mm_hg               19735
humidity_outside          19735
Windspeed                 19735
Visibility                19735
Tdewpoint                 19735
random_variable1          19735
random_variable2          19735
dtype: int64

In [37]:
#dropping the date and lights column
df_energy.drop(['lights','date'], axis=1,inplace=True)
df_energy.head(10)

,Appliances,temp_kitchen,humidity_kitchen,temp_livingroom,humidity_livingroom,temp_laundry,humidity_laundry,temp_office,humidity_office,temp_bathroom,...,temp_parentroom,humidity_parentroom,temp_outside,Press_mm_hg,humidity_outside,Windspeed,Visibility,Tdewpoint,random_variable1,random_variable2
0,60,19.890000,47.596667,19.20,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.500000,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.20,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.600000,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.20,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.700000,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.20,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.800000,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.20,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.900000,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
5,50,19.890000,46.026667,19.20,44.500000,19.79,44.933333,18.890000,45.730000,17.133333,...,17.000000,45.29,6.016667,734.000000,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484
6,60,19.890000,45.766667,19.20,44.500000,19.79,44.900000,18.890000,45.790000,17.100000,...,17.000000,45.29,5.900000,734.100000,92.000000,5.000000,40.000000,4.700000,47.233763,47.233763
7,60,19.856667,45.560000,19.20,44.500000,19.73,44.900000,18.890000,45.863333,17.100000,...,17.000000,45.29,5.916667,734.166667,91.833333,5.166667,40.000000,4.683333,33.039890,33.039890
8,60,19.790000,45.597500,19.20,44.433333,19.73,44.790000,18.890000,45.790000,17.166667,...,17.000000,45.29,5.933333,734.233333,91.666667,5.333333,40.000000,4.666667,31.455702,31.455702
9,70,19.856667,46.090000,19.23,44.400000,19.79,44.863333,18.890000,46.096667,17.100000,...,17.000000,45.29,5.950000,734.300000,91.500000,5.500000,40.000000,4.650000,3.089314,3.089314

In [64]:
#normalizing
scalar = MinMaxScaler()

df_energy_normalize = pd.DataFrame(scalar.fit_transform(df_energy), columns=df_energy.columns)
df_energy_normalize

,Appliances,temp_kitchen,humidity_kitchen,temp_livingroom,humidity_livingroom,temp_laundry,humidity_laundry,temp_office,humidity_office,temp_bathroom,...,temp_parentroom,humidity_parentroom,temp_outside,Press_mm_hg,humidity_outside,Windspeed,Visibility,Tdewpoint,random_variable1,random_variable2
0,0.046729,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.084112,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,...,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.074766,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,...,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.242991,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,...,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.383178,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,...,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.392523,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,...,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [65]:
#splitting the data into independent(X) and target(y) variables
X = df_energy_normalize.drop(['Appliances'], axis=1)
y = df_energy_normalize['Appliances']

In [66]:
X

,temp_kitchen,humidity_kitchen,temp_livingroom,humidity_livingroom,temp_laundry,humidity_laundry,temp_office,humidity_office,temp_bathroom,humidity_bathroom,...,temp_parentroom,humidity_parentroom,temp_outside,Press_mm_hg,humidity_outside,Windspeed,Visibility,Tdewpoint,random_variable1,random_variable2
0,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,0.339590,...,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,0.338487,...,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,0.337585,...,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,0.336583,...,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,0.336583,...,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

In [67]:
#train-test splitting
x_train, x_test, y_train, y_test= train_test_split(X,y, test_size=0.3, random_state=42)

In [68]:
x_train.shape,  x_test.shape, y_train.shape, y_test.shape

((13814, 26), (5921, 26), (13814,), (5921,))

In [69]:
#fit the model to the training dataset
linear_model = LinearRegression()
lin = linear_model.fit(x_train, y_train)
lin

LinearRegression()

In [70]:
#evaluating model on test set
predicted_values = linear_model.predict(x_test)
predicted_values

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

# 1. MAE

In [71]:
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 3)
mae

0.05013362397742957

# 2.

In [73]:
x = df_energy['temp_livingroom'].values.reshape(-1, 1)
y = df_energy['temp_outside_northside']

In [74]:
#fitting the linear model
lin_model = LinearRegression()
lin_model.fit(x,y)

LinearRegression()

In [75]:
pred = lin_model.predict(x)
round(lin_model.score(x,y),2)

0.64

# 3

In [76]:
#WHAT IS THE RSS VALUE in 2 d.p?
rss = np.sum(np.square(predicted_values - y_test))
round(rss,2)

45.35

# 4

In [77]:
#calculating the rmse in 3d.p
rmse= np.sqrt(mean_squared_error(predicted_values, y_test))
round(rmse,3)

0.088

# 5

In [78]:
#calculating the r2_score value in 2 d.p
r_squared = r2_score(y_test,predicted_values)
round(r_squared,2)

0.15

# 6

In [80]:
#Getting the features with the lowest and highest weights

def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df
model_weight = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')
model_weight

                  Features  Linear_Model_Weight
0      humidity_livingroom            -0.456698
1             temp_outside            -0.321860
2          temp_livingroom            -0.236178
3          temp_parentroom            -0.189941
4    humidity_teenagerroom            -0.157595
5         humidity_outside            -0.077671
6         humidity_ironing            -0.044614
7      humidity_parentroom            -0.039800
8            temp_bathroom            -0.015657
9             temp_kitchen            -0.003281
10        random_variable1             0.000770
11        random_variable2             0.000770
12             Press_mm_hg             0.006839
13            temp_ironing             0.010319
14              Visibility             0.012307
15       humidity_bathroom             0.016006
16         humidity_office             0.026386
17             temp_office             0.028981
18               Windspeed             0.029183
19        humidity_outside             0.038049
20        humidity_laundry             0.096048
21       temp_teenagerroom             0.101995
22               Tdewpoint             0.117758
23  temp_outside_northside             0.236425
24            temp_laundry             0.290627
25        humidity_kitchen             0.553547

### RH-2 ('humidity_livingroom') has lowest while RH-1 ('humidity_kitchen') has highest

# 7

In [82]:
ridge_reg = Ridge(alpha = 0.4)
ridge_reg.fit(x_train, y_train)
prediction = ridge_reg.predict(x_test)
ridge_rmse = np.sqrt(mean_squared_error(y_test, prediction))
round(ridge_rmse,3)

0.088

# 8

In [84]:
Lasso_reg = Lasso(alpha = 0.001)
Lasso_reg.fit(x_train, y_train)
prediction = ridge_reg.predict(x_test)
Lasso_pred = Lasso_reg.predict(x_test)

In [85]:
model_weight = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(Lasso_reg, x_train, 'Lasso_Weight')

In [87]:
final_weights = pd.merge(model_weight, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on = 'Features')

In [88]:
np.count_nonzero(final_weights.Lasso_Weight)

7

# 9

In [96]:
Lasso_rmse = (mean_squared_error(y_test, Lasso_pred))


round(Lasso_rmse, 3)

0.009